; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

; =========================================================
; Build Flags (การตั้งค่า Compiler)
; =========================================================
build_flags = 
    ; 1. เปิดใช้งาน USB Serial (CDC) สำหรับดู Serial Monitor ผ่าน USB
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -D HAL_PCD_MODULE_ENABLED
    
    ; 2. เปิดใช้งาน Hardware Serial 3 (PB10, PB11) สำหรับคุยกับ ESP32
    -D ENABLE_HWSERIAL3

; =========================================================
; Serial Monitor & Upload
; =========================================================
monitor_speed = 115200
upload_protocol = stlink