; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; เพิ่มบรรทัดนี้เพื่อขยายขนาด Flash (ช่วยแก้ปัญหาพื้นที่ไม่พอในบางกรณี)
board_build.partitions = huge_app.csv

; ตั้งความเร็ว Monitor
monitor_speed = 115200

; =========================================
; 🚀 ปรับเพิ่มความเร็ว Upload ให้เร็วขึ้น 8 เท่า
; (ถ้าสาย USB ไม่ดีแล้วเกิด Error ค่อยลดลงมาเหลือ 460800 ครับ)
upload_speed = 460800
; =========================================

; รายชื่อไลบรารีที่ต้องใช้ (อัปเดตเปลี่ยนจาก LoRa เป็น nRF24L01)
lib_deps =
    nrf24/RF24 @ ^1.4.8
    mikalhart/TinyGPSPlus @ ^1.0.3
    mprograms/QMC5883LCompass @ ^1.2.3
    madhephaestus/ESP32Servo