; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; Environment สำหรับ STM32F103C6 (Receiver)
[env:genericSTM32F103C6]
platform = ststm32
; เปลี่ยนจาก C6 เป็น C8 เพื่อปลดล็อกพื้นที่ Flash จาก 32KB เป็น 64KB
; (บอร์ด Blue Pill ส่วนใหญ่ใช้ชิปตัวเดียวกัน แต่สกรีนต่างกัน ลองใช้ค่านี้ได้เลย)
board = genericSTM32F103C8
framework = arduino

; ตั้งค่า Upload ผ่าน ST-Link
upload_protocol = stlink
debug_tool = stlink

; =================================================================
; 🚀 เพิ่มบรรทัดเหล่านี้เพื่อแก้ปัญหา "Unable to reset target"
; บังคับให้ OpenOCD ทำ Software Reset แทน เพราะ ST-Link ไม่มีสาย NRST
upload_flags = 
    -c 
    reset_config none

; ถ้าอัปโหลดแล้วขึ้น Error ว่า "UNEXPECTED idcode..." (ชิป Clone)
; ให้ลบเครื่องหมาย ; ข้างหน้า 2 บรรทัดล่างนี้ออกเพื่อเปิดใช้งาน
;    -c 
;    set CPUTAPID 0x2ba01477
; =================================================================

; ไลบรารี (อัปเดตสำหรับ nRF24L01)
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    ricmoo/QRCode @ ^0.0.1
    nrf24/RF24 @ ^1.4.8

; การตั้งค่าลดขนาดไฟล์ (Optimization) แบบจัดเต็ม
build_flags = 
    -D SSD1306_NO_SPLASH
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    ; เพิ่ม 2 บรรทัดนี้สำคัญมาก! ช่วยลดขนาด C Runtime Library
    -specs=nano.specs
    -specs=nosys.specs